export const CLEAR_CUT = "CLEAR_CUT"
export const REMOVE = "REMOVE"
export const INCREASE = "INCREASE"
export const DECREASE = "DECREASE"
export const LOADING = "LOADING"
export const DISPLAY_ITEM = "DISPLAY_ITEM"
